/**********************************************
*   Copyright (C) 2007 CINCOM SYSTEMS, INC.
*   All Rights Reserved
**********************************************/

package org.dbuml.base.controller.ui;

import org.dbuml.base.controller.Util;
import org.dbuml.base.i18n.Translator;
import javax.swing.JOptionPane;

/**
 * A dialog for creating database constraints.
 * @author jgrengbondai
 */
public class ConstraintDlg extends javax.swing.JDialog {
    private EntitiesChooserPanel entityPanel;
    private boolean ok = false;
    
    private static ConstraintDlg dlg;
    
    /** Creates new form ConstraintDlg */
    private ConstraintDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        entityPanel = new EntitiesChooserPanel();
        initComponents();
        centerPanel.add(entityPanel, java.awt.BorderLayout.CENTER);
        this.setTitle(Translator.getInstance().localize("CONSTRAINT_UNIQUE"));
        this.pack();
    }
    
    /**
     * Gets the only instance of this dialog.
     * @return An instance of this dialog.
     */
    public static ConstraintDlg getInstance() {
        if (dlg == null) {
            dlg = new ConstraintDlg(new javax.swing.JFrame(), true);
        }
        return dlg;
    }
    
    /**
     * Selects data.
     * @param data A list of data to select.
     * @return An array of selected data.
     */
    public static String[] selectData(final String[] data) {
        getInstance();
        dlg.initScreen(data);
        dlg.setVisible(true);
        return (dlg.ok ? dlg.entityPanel.getChosenElements() 
                        : new String[] {} );
    }
    
    /**
     * Gets the index name.
     * @return An index name.
     */
    public String getIndexName() {
        return this.indexName.getText();
    }
    
    private void initScreen(String[] data) {
        this.entityPanel.initScreen(data);
        this.indexName.setText("");
    }
    
    private void shutDown() {
        setVisible(false);
//        dispose(); // reusing the dialog, do not dispose.
        //TO DO: When can it be disposed?
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        indexNameLabel = new javax.swing.JLabel();
        indexName = new javax.swing.JTextField();

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        buttonPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        okButton.setText(java.util.ResourceBundle.getBundle("org/dbuml/base/i18n/DBUML").getString("OK_BTN"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText(java.util.ResourceBundle.getBundle("org/dbuml/base/i18n/DBUML").getString("CANCEL_BTN"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 5, 10, 50)));
        indexNameLabel.setText(java.util.ResourceBundle.getBundle("org/dbuml/base/i18n/DBUML").getString("INDEX_LBL"));
        jPanel1.add(indexNameLabel);

        indexName.setPreferredSize(new java.awt.Dimension(165, 20));
        jPanel1.add(indexName);

        centerPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.ok = false;
        this.shutDown();
        evt.getID(); // to keep PMD quiet!
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        String index = this.indexName.getText();
        if (index.equals("") || index.trim().equals("")) {
            Util.showMessageDialog(this, 
                   Translator.getInstance().localize("INDEX_NAME_MSG"),
                                Translator.getInstance().localize(
                                    "UNIQUE_CONSTRAINT"),
                                JOptionPane.ERROR_MESSAGE);
            return;                                    
        }
        
        this.ok = true;
        this.shutDown();
        evt.getID(); // to keep PMD quiet!
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField indexName;
    private javax.swing.JLabel indexNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
