/**********************************************
*   Copyright (C) 2007 CINCOM SYSTEMS, INC.
*   All Rights Reserved
**********************************************/

package org.dbuml.base.controller.ui;


/**
 * Dialog for choosing database entities.
 * @author  jgrengbondai
 */
public class EntitiesChooserDlg extends javax.swing.JDialog {
    private boolean ok = false;
    private static EntitiesChooserDlg dlg;
    private EntitiesChooserPanel entityPanel;
    
    private static final String BUNDLE = "org/dbuml/base/i18n/DBUML";
    
    /**
     * Creates new form EntitiesChooserDlg.
     * @param parent The parent frame.
     * @param modal modal flag.
     */
    public EntitiesChooserDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        entityPanel = new EntitiesChooserPanel();
        this.getContentPane().add(entityPanel, java.awt.BorderLayout.CENTER);
        initComponents();
    }
    
    private static void initDlg() {
        if (dlg == null) {
            dlg = new EntitiesChooserDlg(new javax.swing.JFrame(), true);
        }
    }
    
    /** Get user selected data.
     *@param title The dialog title
     *@param data Array of data to select from.
     *@return An arry of selected data or an empty arrya if nothing is selected.
     */
    public static String[] selectData(String title, final String[] data) {
        String[] retVal = null;
        if (org.dbuml.base.controller.Util.isBatchMode()) {
            retVal = data;
        } else {
            initDlg();
            dlg.initScreen(title, data);
            dlg.setVisible(true);
            retVal = (dlg.ok ? dlg.entityPanel.getChosenElements() 
                            : new String[] {} );
        }
        return retVal;
    }
   
    
    private String[] getChosenElements() {
        return this.entityPanel.getChosenElements();
    }
    
    private void initScreen(String title, String[] data) {
        this.setTitle(title);
        this.entityPanel.initScreen(data);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        okButton.setText(java.util.ResourceBundle.getBundle(BUNDLE).getString("OK_BTN"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.add(okButton);

        cancelButton.setText(java.util.ResourceBundle.getBundle("org/dbuml/base/i18n/DBUML").getString("CANCEL_BTN"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        ok = false;
        this.shutDown();
        evt.getID(); // to keep PMD quiet!
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Add your handling code here:
        ok = true;
        this.shutDown();
        evt.getID(); // to keep PMD quiet!
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        ok = false;
        this.shutDown();
        evt.getID(); // to keep PMD quiet!
    }//GEN-LAST:event_closeDialog
    
    private void shutDown() {
        setVisible(false);
//        dispose(); // reusing the dialog, do not dispose.
        //TO DO: When can it be disposed?
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
